# Generated by Django 3.1.2 on 2023-05-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20230531_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main']},
        ),
    ]
