# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик в кладовке"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/10/
Content-Type: application/json

{
  "name": "ESP32-CAM"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 15,
  "temperature": 24.0
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/15/
Content-Type: application/json
