# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта +
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Ананас",
  "description": "Хорош с шампанским"
}

###

# получение продуктов +
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта +
PATCH {{baseUrl}}/products/4/
Content-Type: application/json

{
  "description": "Очень хорошие"
}

###

# удаление продукта +
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию +
GET {{baseUrl}}/products/?search=ор
Content-Type: application/json

###

# поиск складов, где есть определенный продукт +
GET {{baseUrl}}/stocks/?search=ана
Content-Type: application/json

###

# создание склада +
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Вересаева 2",
  "positions": [
    {
      "product": 3,
      "quantity": 150,
      "price": 250.50
    },
    {
      "product": 1,
      "quantity": 1000,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе +
PATCH {{baseUrl}}/stocks/7/
Content-Type: application/json

{
  "positions": [
    {
      "product": 3,
      "quantity": 350,
      "price": 200.50
    },
    {
      "product": 1,
      "quantity": 1500,
      "price": 80
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=1
Content-Type: application/json


###
# пагинация
GET {{baseUrl}}/products/?page=2

